---
title: "COVID-19"
author: "Mark"
date: "27/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


## Analysis of COVID-19


Download the latest file

```{r}
download.file("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv",destfile = "time_series_covid19_confirmed_global.csv")
```


```{r fig.width=12}
covid <- read_csv("time_series_covid19_confirmed_global.csv")
countries <- c("China","Italy","US","Spain","Germany","Iran","France","Switzerland","United Kingdom","Korea, South","Netherlands","Austria","Belgium","Canada","Norway","Portugal","Brazil","Sweden","Israel","Turkey")
read_csv("time_series_covid19_confirmed_global.csv") %>% 
select(contains("Country"), 5:ncol(covid)) %>% 
  tidyr::gather(Date, Cases, -1) %>% 
  rename(Country = `Country/Region`) %>% 
  mutate(Date = lubridate::mdy(Date)) %>% 
  group_by(Date,Country) %>% 
  summarise(Cases = sum(Cases)) %>% 
  ungroup %>% 
  mutate(NewCases = Cases - dplyr::lag(Cases,default = 0)) %>% 
  filter(Country %in% countries) %>% 
  mutate(NewCases = pmin(NewCases,5000)) %>% 
  ggplot(aes(x = Date, y = fct_relevel(Country,rev(countries)), fill= NewCases)) + geom_tile() + theme(axis.text.x = element_text(angle=90))
```

```{r}
View(covid)
```

